on:
  push:
    branches:
      - feature/lambda-pipeline

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - run: npm install -g npm
            - run: npm ci
            - run: npm run package-upload-publish